### ISSUE TITLE
Google scholar's AAAA record is not found

### ISSUE THREAD

**Issue by sharuijinfriend** [lennylxx/ipv6-hosts#268]
Due to the lack of AAAA record, the output of running update_hosts.sh will be added a '#' character in front of the exsiting one. 

So the line in hosts.out file is like this: `#2404:6800:4008:c06::be scholar.google.com`. And I have to remove '#' manually. 

I guess it will be better if the new hosts_out and original hosts can be merged. I tried to use the merge_snippets.sh but it didn't make sense to me. In merger shell, `cat snippets/??_*.txt >> $new_hosts_file` seems to create a new hosts which consists of all files in the folder named snippets. And the new hosts is same as the original hosts,  having nothing to do with the hosts.out created by update_hosts.sh.

**Comment by lennylxx** [comment]
1. Please read the wiki first https://github.com/lennylxx/ipv6-hosts/wiki/How-to-speed-up
This is already a section says that there are some domains, which don't have AAAA record, and you need to change them manually every time after you run the update script.
2. merge script is for merging multiple snippet files into a whole one. 
You can definitely update one of them and then merge, instead of reverse operation order. 
e.g. `./update_hosts.py snippets/01_google.txt`
